name: AngryWolves
main: com.mikeprimm.bukkit.AngryWolves.AngryWolves
version: "${project.version}-${BUILD_NUMBER}"
author: mikeprimm

permissions:
  angrywolves.wolf-friend:
    description: Will not be attacked by Angry Wolves
    default: op
